name: Install

on: [push, pull_request]

jobs:
  install:
    strategy:
      matrix:
        platform:
          - ubuntu-latest
          - macos-latest
        shell:
          - bash
          - dash
          - ksh
          - sh
          - zsh
        script:
          - beta-install.sh
          - install.sh

    runs-on: ${{matrix.platform}}

    steps:
      - uses: actions/checkout@v2
      - name: Install shell
        run: sudo apt-get install -y ${{ matrix.shell }}
        if: ${{ matrix.shell != 'sh' }}
      - name: Run installation script
        run: ${{ matrix.shell }} ${{ matrix.script }}
